_target_: consistency_policy.teacher.edm_lowdim_workspace.EDMLowdimWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
keypoint_dim: 3
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: dp_test
  project: consistent_policy
  resume: true
  tags: ["${name}", "${task_name}", "${exp_name}", "edm"]
multi_run:
  run_dir: data/outputs/2022.12.29/22.31.27_train_diffusion_unet_hybrid_can_lowdim
  wandb_name_base: dp_test
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
obs_as_local_cond: false
obs_dim: 23
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: consistency_policy.teacher.edm_lowdim_policy.KarrasUnetLowdimPolicy
  inference_mode: none # this will be populated automatically from training.inference_mode, do not set it here
  cond_predict_scale: true
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  action_dim: 10
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_groups: 8
  n_obs_steps: 2
  delta: -1
  noise_scheduler:
    _target_: consistency_policy.diffusion.Karras_Scheduler
    time_min: 0.02
    time_max: 80.0
    rho: 7.0
    bins: 80
    solver: heun
    time_sampler: log_normal
    scaling: boundary
    use_c_in: true
    data_std: .5
    clamp: true
    name: heun80
  obs_as_global_cond: true
  oa_step_convention: true
  obs_as_local_cond: false
  obs_dim: 23
  pred_action_steps_only: false
task:
  abs_action: true
  action_dim: 10
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_lowdim_dataset.RobomimicReplayLowdimDataset
    abs_action: true
    dataset_path: data/robomimic/datasets/can/ph/low_dim_abs.hdf5
    horizon: 16
    max_train_episodes: null
    obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    pad_after: 7
    pad_before: 1
    seed: 42
    use_legacy_normalizer: false
    val_ratio: 0.02
  dataset_path: data/robomimic/datasets/can/ph/low_dim_abs.hdf5
  dataset_type: ph
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_lowdim_runner.RobomimicLowdimRunner
    abs_action: true
    crf: 22
    dataset_path: data/robomimic/datasets/can/ph/low_dim_abs.hdf5
    fps: 10
    max_steps: 400
    n_action_steps: 8
    n_envs: 28
    n_latency_steps: 0
    n_obs_steps: 2
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    past_action: false
    render_hw:
    - 128
    - 128
    test_start_seed: 100000
    train_start_idx: 0
  keypoint_dim: 3
  name: can_lowdim
  obs_dim: 23
  obs_keys:
  - object
  - robot0_eef_pos
  - robot0_eef_quat
  - robot0_gripper_qpos
  task_name: can
task_name: can_lowdim
training:
  inference_mode: false # Setting this to true disables the teacher, warm start, and training loop
  online_rollouts: true # Setting this to false disables the env_runner
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 2000
  resume: false
  resume_path: ???
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
  val_sample_every: 5
  output_dir: None
val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false